Add in tests for plabort calls for the tests for bindings other than C. This looks for the text "PLPLOT ERROR" appearing on stderr from the examples. ctest will now report a failure for calls to plabort as well as plexit / crashes.
svn path=/trunk/; revision=7817

diff --git a/test/test_ada.sh.in b/test/test_ada.sh.in
--- a/test/test_ada.sh.in
+++ b/test/test_ada.sh.in
@@ -28,9 +28,15 @@
 
 # Do the standard non-interactive examples.
 for index in 01 02 04 10 12 thick01 thick02 thick04 thick10 thick12; do
-  $adadir/x${index}a -dev $device -o ${OUTPUT_DIR}/x${index}a.$dsuffix $options
+  $adadir/x${index}a -dev $device -o ${OUTPUT_DIR}/x${index}a.$dsuffix $options 2> test.error
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
+  fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
   fi
 done
diff --git a/test/test_f77.sh.in b/test/test_f77.sh.in
--- a/test/test_f77.sh.in
+++ b/test/test_f77.sh.in
@@ -34,10 +34,16 @@ if test "yes@HAVE_F77PARSE_CL_TRUE@" = "yes"; then
 
 # Do non-standard example 16a because it illustrates plshade functionality
 # with cmap1 (and also because the result looks nice.)
-  $f77dir/x16af -dev $device -o ${OUTPUT_DIR}/x16af.$dsuffix $options
+  $f77dir/x16af -dev $device -o ${OUTPUT_DIR}/x16af.$dsuffix $options 2> test.error
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
+  fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
   fi
 
 # Do the standard non-interactive examples.
@@ -45,11 +51,18 @@ if test "yes@HAVE_F77PARSE_CL_TRUE@" = "yes"; then
 # skip 21 because it delivers variable results depending on computer timing
 # and load (and not implemented yet).
   for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 19 22 23; do
-    $f77dir/x${index}f -dev $device -o ${OUTPUT_DIR}/x${index}f.$dsuffix $options
+    $f77dir/x${index}f -dev $device -o ${OUTPUT_DIR}/x${index}f.$dsuffix $options 2> test.error
     status_code=$?
     if [ "$status_code" -ne 0 ]; then
       exit $status_code
     fi
+    # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+    # exit code.
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+      exit 1
+    fi
+
   done
 else
 # Fall back to this method if this fortran platform does not have
@@ -57,13 +70,19 @@ else
 # for this method.
 # Do non-standard example 16a because it illustrates plshade functionality
 # with cmap1 (and also because the result looks nice.)
-  $f77dir/x16af <<EOF >/dev/null
+  $f77dir/x16af <<EOF 2> test.error
 $device
-${OUTPUT_DIR}/x16af.$dsuffix
+${OUTPUT_DIR}/x16af.$dsuffix 
 EOF
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
+  fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
   fi
 
 # Do the standard non-interactive examples.
@@ -71,7 +90,7 @@ EOF
 # skip 21 because it delivers variable results depending on computer timing
 # and load (and not implemented yet).
   for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 19 22 23; do
-     $f77dir/x${index}f <<EOF >/dev/null
+     $f77dir/x${index}f <<EOF 2> test.error
 $device
 ${OUTPUT_DIR}/x${index}f.$dsuffix
 EOF
@@ -79,5 +98,12 @@ EOF
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
   fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
+  fi
+
   done
 fi
diff --git a/test/test_java.sh.in b/test/test_java.sh.in
--- a/test/test_java.sh.in
+++ b/test/test_java.sh.in
@@ -44,12 +44,19 @@ fi
 
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 20 21 22 23 24 25 26; do
   if test "@WIN32@" = "1"; then
-    java -classpath ${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}j.$dsuffix $options
+    java -classpath ${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}j.$dsuffix $options 2> test.error
   else
-    java -classpath ${javadir}:${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}j.$dsuffix $options
+    java -classpath ${javadir}:${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}j.$dsuffix $options 2> test.error
   fi
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
   fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
+  fi
+
 done
diff --git a/test/test_octave.sh.in b/test/test_octave.sh.in
--- a/test/test_octave.sh.in
+++ b/test/test_octave.sh.in
@@ -31,7 +31,7 @@ echo $TOPDIR
 export LD_LIBRARY_PATH=$TOPDIR/src:$TOPDIR/lib/csa:$TOPDIR/lib/nn
 
 # Launch an Octave script that exercises all the demos
-$octave -f -q -p $octavedir <<EOF
+$octave -f -q -p $octavedir <<EOF 2> test.error
 plplot_stub;
 t = split("$options", "-"); t(1,:)="";
 for i=1:rows(t)
@@ -88,3 +88,10 @@ status_code=$?
 if [ "$status_code" -ne 0 ]; then
   exit $status_code
 fi
+# Look for any PLPLOT ERROR messages from plwarn that do not result in an
+# exit code.
+is_error=`grep -l 'PLPLOT ERROR' test.error`
+if test -n "$is_error"; then
+  exit 1
+fi
+
diff --git a/test/test_perl.sh.in b/test/test_perl.sh.in
--- a/test/test_perl.sh.in
+++ b/test/test_perl.sh.in
@@ -38,9 +38,15 @@ else
 fi
 
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 19 20 21 22 23 24 25 26; do
-  $perldir/x${index}.pl -dev $device -o ${OUTPUT_DIR}/x${index}pdl.$dsuffix $options
+  $perldir/x${index}.pl -dev $device -o ${OUTPUT_DIR}/x${index}pdl.$dsuffix $options 2> test.error
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
+  fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
   fi
 done
diff --git a/test/test_python.sh.in b/test/test_python.sh.in
--- a/test/test_python.sh.in
+++ b/test/test_python.sh.in
@@ -31,9 +31,16 @@
 # Skip 21 if using Numeric - it doesn't work
 # For 24 you need special fonts installed to get good result.
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 22 23 24 25 26 @NUMPY_EXAMPLES@ ; do
-  @PYTHON_EXECUTABLE@ $pythondir/x$index -dev $device -o ${OUTPUT_DIR}/x${index}p.$dsuffix $options
+  @PYTHON_EXECUTABLE@ $pythondir/x$index -dev $device -o ${OUTPUT_DIR}/x${index}p.$dsuffix $options 2> test.error
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
   fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
+  fi
+
 done
diff --git a/test/test_tcl.sh.in b/test/test_tcl.sh.in
--- a/test/test_tcl.sh.in
+++ b/test/test_tcl.sh.in
@@ -27,7 +27,7 @@ cd $OUTPUT_DIR
 results=`pwd`
 export results
 cd $tcldir
-pltcl -dev $device -o $results/plot.$dsuffix $options <<EOF
+pltcl -dev $device -o $results/plot.$dsuffix $options <<EOF 2> test.error
 plinit
 source plot.tcl
 plot stats.log {1 4}
@@ -40,7 +40,13 @@ status_code=$?
 if [ "$status_code" -ne 0 ]; then
   exit $status_code
 fi
-pltcl -dev $device -o $results/plgrid.$dsuffix $options <<EOF
+# Look for any PLPLOT ERROR messages from plwarn that do not result in an
+# exit code.
+is_error=`grep -l 'PLPLOT ERROR' test.error`
+if test -n "$is_error"; then
+  exit 1
+fi
+pltcl -dev $device -o $results/plgrid.$dsuffix $options <<EOF 2> test.error
 plinit
 source plgrid.tcl
 plgrid
@@ -50,14 +56,26 @@ status_code=$?
 if [ "$status_code" -ne 0 ]; then
   exit $status_code
 fi
+# Look for any PLPLOT ERROR messages from plwarn that do not result in an
+# exit code.
+is_error=`grep -l 'PLPLOT ERROR' test.error`
+if test -n "$is_error"; then
+  exit 1
+fi
 # Skip 14th example because requires two output files.
 # Skip 17th example because it is not implemented (and if it was, it
 # would be interactive only).
 # Other examples are not yet implemented.
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 22; do
-  ./x${index} -dev $device -o $results/x${index}t.$dsuffix $options
+  ./x${index} -dev $device -o $results/x${index}t.$dsuffix $options 2> test.error
   status_code=$?
   if [ "$status_code" -ne 0 ]; then
     exit $status_code
+  fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+  is_error=`grep -l 'PLPLOT ERROR' test.error`
+  if test -n "$is_error"; then
+    exit 1
   fi
 done
