Fix trailing space issues on most files
This fix was done piecemeal and sometimes with checks on the
find results that no binary files were affected rather than excluding
them from the start (based on the rules in .gitattributes).  But
effectively the following command was used (and should be used for
future changes of this type):

sed -i -e 's?  *$??' $(find . -type f |grep -E -v '\.git|\.pgm|\.gif|\.jpg|\.cgm|\.map|\.dbf|\.prj|\.shp|\.shx|\.fnt|debian/|rpm/|lib/|\.patch|libqhull/src/mem.h|COPYING.LIB' | xargs grep -l '  *$')

where the exclude pattern is designed to exclude from this change .git
directory files; all binary files according to the rules in
.gitattributes; debian, rpm, and lib directory and subdirectory files;
*.patch files; a particular epa_build file, and the LGPL licensing
text file from this change.

Tested by: Alan W. Irwin <airwin@users.sourceforge.net> on Linux
(Debian Jessie) using the command

scripts/comprehensive_test.sh

to comprehensively test _both_ the noninteractive and interactive
components of PLplot.  The results showed no obvious configure, build,
or run-time errors, and PostScript differences only occurred for the
well-known and long-standing ocaml case.

N.B. This test is obviously not complete, but it is the most
comprehensive we have (other than daily use by large numbers of users
on all platforms) so at least it is a good indication that if some
error has been introduced by this extremely intrusive commit, it is
quite subtle and will likely be encountered by few users.

diff --git a/plplot_test/plplot-test-interactive.sh.in b/plplot_test/plplot-test-interactive.sh.in
--- a/plplot_test/plplot-test-interactive.sh.in
+++ b/plplot_test/plplot-test-interactive.sh.in
@@ -30,7 +30,7 @@ echo '
 Usage: plplot-test-interactive.sh [OPTIONS]
 
 Options:
-   [--device=DEVICES_LIST] 
+   [--device=DEVICES_LIST]
        where DEVICES_LIST is one of more devices specified as a
        blank-delimited string (e.g., --device=xwin or
        --device="qtwidget extqt").  Note each specified device must be
@@ -127,7 +127,7 @@ for device in $DEVICES_LIST ; do
     eval pld_device='$'PLD_$device
     if [ ! "$pld_device" = "ON" ] ; then
 	echo "$device is either not configured or not used for interactive tests."
-	usage 1 1>&2 
+	usage 1 1>&2
     fi
 done
 
@@ -227,7 +227,7 @@ for index in $INDEX_LIST ; do
     # Look for any PLPLOT ERROR messages from plwarn that do not result in an exit code.
     is_error=`grep -l 'PLPLOT ERROR' test.error`
     if [ -n "$is_error" ] ; then
-        echo "ERROR indicated by 'PLPLOT ERROR' in stderr for ${COMMAND[$index]}" 
+        echo "ERROR indicated by 'PLPLOT ERROR' in stderr for ${COMMAND[$index]}"
 	OVERALL_STATUS_CODE=1
     fi
     popd
