Extirpate anything having to do with Fortran 77.  These changes were quite intrusive because I went out of my way to search for any mention of "77" in our source tree and followed up with an edit or deletion of the file where appropriate.
Tested by Alan W. Irwin <airwin@users.sourceforge.net> on Linux
using the test_noninteractive target in the build tree.

More comprehensive tests to follow.

svn path=/trunk/; revision=12725

diff --git a/plplot_test/test_f95.sh.in b/plplot_test/test_f95.sh.in
--- a/plplot_test/test_f95.sh.in
+++ b/plplot_test/test_f95.sh.in
@@ -29,113 +29,50 @@
 lang="f95"
 export index lang
 
-if [ "yes@HAVE_F77PARSE_CL_TRUE@" = "yes" ] ; then
-# This stanza only works if fortran has command-line parsing capability.
-# However, this is the preferred method because it allows access to
-# command-line parsing of the $options (e.g., familying options for png
-# and jpeg devices) that have been passed from plplot-test.sh
+# It is assumed here that fortran has command-line parsing capability.
 
 # Do non-standard example 16a because it illustrates plshade functionality
 # with cmap1 (and also because the result looks nice.)
+if [ "$verbose_test" ] ; then
+    echo "x16af"
+fi
+index="16a"
+$DEBUG_CMD "$f95dir"/x${index}f -dev $device -o "${OUTPUT_DIR}"/x${index}f95%n.$dsuffix $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
+status_code=$?
+cat test.error
+if [ "$status_code" -ne 0 ] ; then
+    exit $status_code
+fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+is_error=`grep -l 'PLPLOT ERROR' test.error`
+if [ -n "$is_error" ] ; then
+    exit 1
+fi
+
+
+# Do the standard non-interactive examples.
+for index in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 33; do
     if [ "$verbose_test" ] ; then
-	echo "x16af"
+	echo "x${index}f"
     fi
-    index="16a"
-    $DEBUG_CMD "$f95dir"/x${index}f -dev $device -o "${OUTPUT_DIR}"/x${index}f95%n.$dsuffix $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
-    status_code=$?
+    if [ "${index}" = "14" ] ; then
+	echo "${OUTPUT_DIR}"/x${index}a${lang}%n.$dsuffix | \
+	    $DEBUG_CMD "$f95dir"/x${index}f -dev $device -o "${OUTPUT_DIR}"/x${index}${lang}%n.$dsuffix \
+	    $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
+	status_code=$?
+    else
+	$DEBUG_CMD "$f95dir"/x${index}f -dev $device -o "${OUTPUT_DIR}"/x${index}f95%n.$dsuffix $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
+	status_code=$?
+    fi
     cat test.error
     if [ "$status_code" -ne 0 ] ; then
 	exit $status_code
     fi
-  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
-  # exit code.
+    # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+    # exit code.
     is_error=`grep -l 'PLPLOT ERROR' test.error`
     if [ -n "$is_error" ] ; then
 	exit 1
     fi
-
-
-# Do the standard non-interactive examples.
-    for index in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 33; do
-	if [ "$verbose_test" ] ; then
-	    echo "x${index}f"
-	fi
-	if [ "${index}" = "14" ] ; then
-	    echo "${OUTPUT_DIR}"/x${index}a${lang}%n.$dsuffix | \
-	    $DEBUG_CMD "$f95dir"/x${index}f -dev $device -o "${OUTPUT_DIR}"/x${index}${lang}%n.$dsuffix \
-      $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
-      status_code=$?
-	else
-	    $DEBUG_CMD "$f95dir"/x${index}f -dev $device -o "${OUTPUT_DIR}"/x${index}f95%n.$dsuffix $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
-	    status_code=$?
-	fi
-	cat test.error
-	if [ "$status_code" -ne 0 ] ; then
-	    exit $status_code
-	fi
-    # Look for any PLPLOT ERROR messages from plwarn that do not result in an
-    # exit code.
-	is_error=`grep -l 'PLPLOT ERROR' test.error`
-	if [ -n "$is_error" ] ; then
-	    exit 1
-	fi
-    done
-else
-# Fall back to this method if this fortran platform does not have
-# command-line parsing capability.  Command-line $options must be ignored
-# for this method.
-# Do non-standard example 16a because it illustrates plshade functionality
-# with cmap1 (and also because the result looks nice.)
-    if [ "$verbose_test" ] ; then
-	echo "x16af"
-    fi
-    index="16a"
-    $DEBUG_CMD "$f95dir"/x${index}f <<EOF 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
-$device
-"${OUTPUT_DIR}"/x${index}f95%n.$dsuffix
-EOF
-  status_code=$?
-  cat test.error
-  if [ "$status_code" -ne 0 ] ; then
-      exit $status_code
-  fi
-  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
-  # exit code.
-  is_error=`grep -l 'PLPLOT ERROR' test.error`
-  if [ -n "$is_error" ] ; then
-      exit 1
-  fi
-
-
-# Do the standard non-interactive examples.
-  for index in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 33; do
-      if [ "$verbose_test" ] ; then
-	  echo "x${index}f"
-      fi
-      if [ "${index}" = "14" ] ; then
-	  $DEBUG_CMD "$f95dir"/x${index}f <<EOF 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
-$device
-"${OUTPUT_DIR}"/x${index}f95%n.$dsuffix
-$device
-"${OUTPUT_DIR}"/x${index}af95%n.$dsuffix
-EOF
-	  status_code=$?
-      else
-	  $DEBUG_CMD "$f95dir"/x${index}f <<EOF 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
-$device
-"${OUTPUT_DIR}"/x${index}f95%n.$dsuffix
-EOF
-	  status_code=$?
-      fi
-      cat test.error
-      if [ "$status_code" -ne 0 ] ; then
-	  exit $status_code
-      fi
-  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
-  # exit code.
-      is_error=`grep -l 'PLPLOT ERROR' test.error`
-      if [ -n "$is_error" ] ; then
-	  exit 1
-      fi
-  done
-fi
+done
