Make "if" syntax more consistent.  [ ] preferred to test, string comparisons done with "=" rather than "==" (already taken care of by recent Andrew Ross commit), and uniformly apply quotes to second argument of string comparison.
svn path=/trunk/; revision=9264

diff --git a/plplot_test/test_octave.sh.in b/plplot_test/test_octave.sh.in
--- a/plplot_test/test_octave.sh.in
+++ b/plplot_test/test_octave.sh.in
@@ -62,7 +62,7 @@ else
 # These require octave-2.1.50 so comment out since not everybody has
 # this.
 
-	    for i=[1:7 8 9 13 15 16];
+	    for i=[1:7 8 9 13 15 16] ;
 	    if (verbose_test)
 		printf("p%d\n",i);
 		endif
@@ -74,8 +74,8 @@ else
 #For file output 17 is not suitable, and 19 is not done
 #(and should probably be dropped anyway since the map stuff is not
 #in the API that is supposed to be common to all front ends.)
-		failed = [];
-		for i=[1:16 18 20:31 ];
+		failed = [] ;
+		for i=[1:16 18 20:31 ] ;
 		ofile = sprintf("${OUTPUT_DIR}/x%.2d${lang}_${dsuffix}.txt",i);
 		strm = fopen(ofile,"w");
 		cmd = sprintf("x%.2dc",i);
@@ -98,7 +98,7 @@ else
     if i == 14  
       file2 = sprintf("${OUTPUT_DIR}/x%.2da${lang}.${dsuffix}",i);
     endif
-    eval(cmd, "failed = [failed, i];");
+    eval(cmd, "failed = [failed, i] ;");
     fclose(strm);
     clear file2;
 endfor
@@ -114,14 +114,14 @@ if ! isempty (failed)
     exit (1);
 endif
 EOF
-    status_code=$?
-    cat test.error
-    if [ "$status_code" -ne 0 ]; then
-	exit $status_code
-    fi
+status_code=$?
+cat test.error
+if [ "$status_code" -ne 0 ] ; then
+    exit $status_code
+fi
 # Look for any PLPLOT ERROR messages from plwarn that do not result in an
 # exit code.
-    is_error=`grep -l 'PLPLOT ERROR' test.error`
-    if test -n "$is_error"; then
-	exit 1
-    fi
+is_error=`grep -l 'PLPLOT ERROR' test.error`
+if [-n "$is_error" ] ; then
+    exit 1
+fi
