Use proper error handling for special x01cc example.
Put that example last so that errors in it do not interfere with running
the standard examples first.


svn path=/trunk/; revision=10970

diff --git a/plplot_test/test_cxx.sh.in b/plplot_test/test_cxx.sh.in
--- a/plplot_test/test_cxx.sh.in
+++ b/plplot_test/test_cxx.sh.in
@@ -30,11 +30,6 @@
 lang="cxx"
 export index lang 
 
-# x01cc is a C++ alternative that has no corresponding examples for the
-# other front ends.
-index=01c
-$DEBUG_CMD "$cxxdir"/x01cc${exesuffix} -dev $device -o "${OUTPUT_DIR}"/x01cc%n.$dsuffix $options
-
 # Do the standard non-interactive examples.
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 19 20 \
     21 22 23 24 25 26 27 28 30 31 ${critical_examples}; do
@@ -61,3 +56,22 @@ for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 18 19 20 \
 	exit 1
     fi
 done
+
+# x01cc is a C++ alternative that has no corresponding examples for the
+# other front ends.
+if [ "$verbose_test" ] ; then
+    echo "x01cc"
+fi
+index=01c
+$DEBUG_CMD "$cxxdir"/x01cc${exesuffix} -dev $device -o "${OUTPUT_DIR}"/x01cc%n.$dsuffix $options 2> test.error >| "${OUTPUT_DIR}"/x${index}${lang}_${dsuffix}.txt
+status_code=$?
+cat test.error
+if [ "$status_code" -ne 0 ] ; then
+    exit $status_code
+fi
+  # Look for any PLPLOT ERROR messages from plwarn that do not result in an
+  # exit code.
+is_error=`grep -l 'PLPLOT ERROR' test.error`
+if [ -n "$is_error" ] ; then
+    exit 1
+fi
