Clean up indentation issues.
svn path=/trunk/; revision=9263

diff --git a/plplot_test/test_ada.sh.in b/plplot_test/test_ada.sh.in
--- a/plplot_test/test_ada.sh.in
+++ b/plplot_test/test_ada.sh.in
@@ -30,32 +30,32 @@
 # Skip 17 because it is interactive.
 lang="a"
 for index in \
-01 02 03 04 05 06 07 08 09 \
-10 11 12 13 14 15 16 18 19 20 \
-21 22 23 24 25 26 27 28 29 30 31 \
-thick01 thick02 thick03 thick04 thick05 thick06 thick07 thick08 thick09 \
-thick10 thick11 thick12 thick13 thick14 thick15 thick16 thick18 thick19 thick20 \
-thick21 thick22 thick23 thick24 thick25 thick26 thick27 thick28 thick29 thick30 thick31; do
-  if [ "$verbose_test" ]; then
-    echo "x${index}"
-  fi
-  if [ "$index" = "14" -o "$index" = "thick14" ] ; then
-    $adadir/x${index}${lang} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt << EOF
+    01 02 03 04 05 06 07 08 09 \
+    10 11 12 13 14 15 16 18 19 20 \
+    21 22 23 24 25 26 27 28 29 30 31 \
+    thick01 thick02 thick03 thick04 thick05 thick06 thick07 thick08 thick09 \
+    thick10 thick11 thick12 thick13 thick14 thick15 thick16 thick18 thick19 thick20 \
+    thick21 thick22 thick23 thick24 thick25 thick26 thick27 thick28 thick29 thick30 thick31; do
+    if [ "$verbose_test" ]; then
+	echo "x${index}"
+    fi
+    if [ "$index" = "14" -o "$index" = "thick14" ] ; then
+	$adadir/x${index}${lang} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt << EOF
 ${OUTPUT_DIR}/x${index}a${lang}%n.$dsuffix
 EOF
-    status_code=$?
-  else
-    $adadir/x${index}${lang} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt
-    status_code=$?
-  fi
-  cat test.error
-  if [ "$status_code" -ne 0 ]; then
-    exit $status_code
-  fi
+	status_code=$?
+    else
+	$adadir/x${index}${lang} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt
+	status_code=$?
+    fi
+    cat test.error
+    if [ "$status_code" -ne 0 ]; then
+	exit $status_code
+    fi
   # Look for any PLPLOT ERROR messages from plwarn that do not result in an
   # exit code.
-  is_error=`grep -l 'PLPLOT ERROR' test.error`
-  if test -n "$is_error"; then
-    exit 1
-  fi
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+	exit 1
+    fi
 done
diff --git a/plplot_test/test_diff.sh.in b/plplot_test/test_diff.sh.in
--- a/plplot_test/test_diff.sh.in
+++ b/plplot_test/test_diff.sh.in
@@ -27,101 +27,100 @@ ret=0
 for lang in c++ f77 f95 java octave python tcl perl ada adathick ocaml ; do
 
   # Check which suffix is used for this binding
-  case $lang in 
-    c++)
-      xsuffix=
-      suffix=cxx
-      ;;
-    f77)
-      xsuffix=
-      suffix=f
-      ;;
-    f95)
-      xsuffix=
-      suffix=f95
-      ;;
-    java)
-      xsuffix=
-      suffix=j
-      ;;
-    octave)
-      xsuffix=
-      suffix=o
-      ;;
-    python)
-      xsuffix=
-      suffix=p
-      ;;
-    tcl)
-      xsuffix=
-      suffix=t
-      ;;
-    perl)
-      xsuffix=
-      suffix=pdl
-      ;;
-    ada)
-      xsuffix=
-      suffix=a
-      ;;
-    adathick)
-      xsuffix=
-      suffix=a
-      ;;
-    ocaml)
-      xsuffix=
-      suffix=ocaml
-      ;;
-  esac
+    case $lang in 
+	c++)
+	    xsuffix=
+	    suffix=cxx
+	    ;;
+	f77)
+	    xsuffix=
+	    suffix=f
+	    ;;
+	f95)
+	    xsuffix=
+	    suffix=f95
+	    ;;
+	java)
+	    xsuffix=
+	    suffix=j
+	    ;;
+	octave)
+	    xsuffix=
+	    suffix=o
+	    ;;
+	python)
+	    xsuffix=
+	    suffix=p
+	    ;;
+	tcl)
+	    xsuffix=
+	    suffix=t
+	    ;;
+	perl)
+	    xsuffix=
+	    suffix=pdl
+	    ;;
+	ada)
+	    xsuffix=
+	    suffix=a
+	    ;;
+	adathick)
+	    xsuffix=
+	    suffix=a
+	    ;;
+	ocaml)
+	    xsuffix=
+	    suffix=ocaml
+	    ;;
+    esac
 
-  missing=""
-  different=""
-  diffstdout=""
-  missingstdout=""
+    missing=""
+    different=""
+    diffstdout=""
+    missingstdout=""
 
   # Assume that if example 1 is missing then the language is
   # not implemented.
-  if [ -f x${xsuffix}01${suffix}.psc ] ; then
-    
+    if [ -f x${xsuffix}01${suffix}.psc ] ; then
+	
   # Standard non-interactive examples
   # Skip example 17 because it is interactive
-  for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 14a 15 16 18 19 20 \
-      21 22 23 24 25 26 27 28 29 30 31 ; do
-    if [ ! -f x${xsuffix}${index}c.psc ] ; then
-      echo "C example ${index} is missing"
-    else
-      if [ ! -f x${xsuffix}${index}${suffix}.psc ] ; then
-        missing="${missing} ${index}"
-      else
-        @TAIL_EXECUTABLE@ --lines=+9 x${xsuffix}${index}c.psc > test1.psc
-        @TAIL_EXECUTABLE@ --lines=+9 x${xsuffix}${index}${suffix}.psc > test2.psc
-        @DIFF_EXECUTABLE@ -q test1.psc test2.psc 2>&1 > /dev/null
-        if [ $? != 0 ] ; then
-          different="${different} ${index}"
-        fi
-        if [ "$index" != "14a" ] ; then
-          if [ -f x${xsuffix}${index}${suffix}_psc.txt ] ; then
-            @DIFF_EXECUTABLE@ -q x${xsuffix}${index}c_psc.txt x${xsuffix}${index}${suffix}_psc.txt 2>&1 > /dev/null
-            if [ $? != 0 ] ; then
-              diffstdout="${diffstdout} ${index}"
-            fi
-          else
-            missingstdout="${missingstdout} ${index}"
-          fi
-        fi
-      fi
-    fi
-  done
-  echo "${lang}"
-  echo "  Missing examples            : ${missing}"
-  echo "  Differing postscript output : ${different}"
-  echo "  Missing stdout              : ${missingstdout}"
-  echo "  Differing stdout            : ${diffstdout}"
-  if [ "${different}" != "" -o "${diffstdout}" != "" ] ; then
-    ret=1
-  fi
-  fi 
+	for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 14a 15 16 18 19 20 \
+	    21 22 23 24 25 26 27 28 29 30 31 ; do
+	    if [ ! -f x${xsuffix}${index}c.psc ] ; then
+		echo "C example ${index} is missing"
+	    else
+		if [ ! -f x${xsuffix}${index}${suffix}.psc ] ; then
+		    missing="${missing} ${index}"
+		else
+		    @TAIL_EXECUTABLE@ --lines=+9 x${xsuffix}${index}c.psc > test1.psc
+		    @TAIL_EXECUTABLE@ --lines=+9 x${xsuffix}${index}${suffix}.psc > test2.psc
+		    @DIFF_EXECUTABLE@ -q test1.psc test2.psc 2>&1 > /dev/null
+		    if [ $? != 0 ] ; then
+			different="${different} ${index}"
+		    fi
+		    if [ "$index" != "14a" ] ; then
+			if [ -f x${xsuffix}${index}${suffix}_psc.txt ] ; then
+			    @DIFF_EXECUTABLE@ -q x${xsuffix}${index}c_psc.txt x${xsuffix}${index}${suffix}_psc.txt 2>&1 > /dev/null
+			    if [ $? != 0 ] ; then
+				diffstdout="${diffstdout} ${index}"
+			    fi
+			else
+			    missingstdout="${missingstdout} ${index}"
+			fi
+		    fi
+		fi
+	    fi
+	done
+	echo "${lang}"
+	echo "  Missing examples            : ${missing}"
+	echo "  Differing postscript output : ${different}"
+	echo "  Missing stdout              : ${missingstdout}"
+	echo "  Differing stdout            : ${diffstdout}"
+	if [ "${different}" != "" -o "${diffstdout}" != "" ] ; then
+	    ret=1
+	fi
+    fi 
 done
 
 exit ${ret}
-
diff --git a/plplot_test/test_java.sh.in b/plplot_test/test_java.sh.in
--- a/plplot_test/test_java.sh.in
+++ b/plplot_test/test_java.sh.in
@@ -37,37 +37,37 @@
 # Set up option to point to java bindings jar file and wrapper if needed.
 lang="j"
 if test -n "$PLPLOT_JAVA_WRAP_DIR" ; then
-  JAVA_TEST_OPTS="-Dplplot.libdir=$PLPLOT_JAVA_WRAP_DIR"
+    JAVA_TEST_OPTS="-Dplplot.libdir=$PLPLOT_JAVA_WRAP_DIR"
 fi
 if test -z "$PLPLOT_CLASSPATH" ; then
-  PLPLOT_CLASSPATH=@JAVADATA_HARDDIR@/plplot.jar
+    PLPLOT_CLASSPATH=@JAVADATA_HARDDIR@/plplot.jar
 fi
 if test "@WIN32@" != "1" ; then
-  PLPLOT_CLASSPATH=${javadir}:${PLPLOT_CLASSPATH}
+    PLPLOT_CLASSPATH=${javadir}:${PLPLOT_CLASSPATH}
 fi
 
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 20 21 22 23 24 25 26 27 28 29 30 31 ; do
-  if [ "$verbose_test" ]; then
-    echo "x${index}"
-  fi
-  if [ "$index" = "14" ] ; then
-    java -classpath ${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt << EOF
+    if [ "$verbose_test" ]; then
+	echo "x${index}"
+    fi
+    if [ "$index" = "14" ] ; then
+	java -classpath ${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt << EOF
 ${OUTPUT_DIR}/x${index}a${lang}%n.$dsuffix
 EOF
-    status_code=$?
-  else
-    java -classpath ${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt
-    status_code=$?
-  fi
-  cat test.error
-  if [ "$status_code" -ne 0 ]; then
-    exit $status_code
-  fi
+	status_code=$?
+    else
+	java -classpath ${PLPLOT_CLASSPATH} ${JAVA_TEST_OPTS} plplot.examples.x${index} -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt
+	status_code=$?
+    fi
+    cat test.error
+    if [ "$status_code" -ne 0 ]; then
+	exit $status_code
+    fi
   # Look for any PLPLOT ERROR messages from plwarn that do not result in an
   # exit code.
-  is_error=`grep -l 'PLPLOT ERROR' test.error`
-  if test -n "$is_error"; then
-    exit 1
-  fi
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+	exit 1
+    fi
 
 done
diff --git a/plplot_test/test_octave.sh.in b/plplot_test/test_octave.sh.in
--- a/plplot_test/test_octave.sh.in
+++ b/plplot_test/test_octave.sh.in
@@ -43,51 +43,51 @@ endif
 
 # Check verbose_test variable
 if (strcmp(getenv("verbose_test"),"on") == 1)
-  verbose_test = 1;
+verbose_test = 1;
 else
-  verbose_test = 0;
-endif
+    verbose_test = 0;
+    endif
 
-plplot_stub;
-t = split("$options", "-"); 
-if (t); t(1,:)=""; endif;
-for i=1:rows(t)
-    tt = deblank (t(i,:)); len = length(tt);
-    ix = index(tt," ");
-    if (ix == 0); ix = len; len = 0; endif
-    plsetopt(tt(1:ix), tt(ix+1:len));
-endfor
+    plplot_stub;
+    t = split("$options", "-"); 
+    if (t); t(1,:)=""; endif;
+	for i=1:rows(t)
+	tt = deblank (t(i,:)); len = length(tt);
+	ix = index(tt," ");
+	if (ix == 0); ix = len; len = 0; endif
+	    plsetopt(tt(1:ix), tt(ix+1:len));
+	    endfor
 
 # p7 works OK with plmeta, e.g., but not ps or psc. pleop/plbop issue?
 # These require octave-2.1.50 so comment out since not everybody has
 # this.
 
-for i=[1:7 8 9 13 15 16];
-   if (verbose_test)
-     printf("p%d\n",i);
-   endif
-   figure(i,"$device",sprintf("${OUTPUT_DIR}/p%d%%n.$dsuffix",i));
-   feval(sprintf("p%d",i))
-   closefig
-endfor
+	    for i=[1:7 8 9 13 15 16];
+	    if (verbose_test)
+		printf("p%d\n",i);
+		endif
+		figure(i,"$device",sprintf("${OUTPUT_DIR}/p%d%%n.$dsuffix",i));
+		feval(sprintf("p%d",i))
+		closefig
+		endfor
 #plot equivalent of x??c examples.  These only required octave-2.0.x
 #For file output 17 is not suitable, and 19 is not done
 #(and should probably be dropped anyway since the map stuff is not
 #in the API that is supposed to be common to all front ends.)
-failed = [];
-for i=[1:16 18 20:31 ];
-    ofile = sprintf("${OUTPUT_DIR}/x%.2d${lang}_${dsuffix}.txt",i);
-    strm = fopen(ofile,"w");
-      cmd = sprintf("x%.2dc",i);
-    if (verbose_test)
-      printf("%s\n",cmd);
-    endif
-    t = split("$options", "-"); t(1,:)="";
-    for j=1:rows(t)
-        tt = deblank (t(j,:)); len = length(tt);
-	ix = index(tt," ");
-	if (ix == 0); ix = len; len = 0; endif
-	plSetOpt(deblank(tt(1:ix)), tt(ix:len));
+		failed = [];
+		for i=[1:16 18 20:31 ];
+		ofile = sprintf("${OUTPUT_DIR}/x%.2d${lang}_${dsuffix}.txt",i);
+		strm = fopen(ofile,"w");
+		cmd = sprintf("x%.2dc",i);
+		if (verbose_test)
+		    printf("%s\n",cmd);
+		    endif
+		    t = split("$options", "-"); t(1,:)="";
+		    for j=1:rows(t)
+		    tt = deblank (t(j,:)); len = length(tt);
+		    ix = index(tt," ");
+		    if (ix == 0); ix = len; len = 0; endif
+			plSetOpt(deblank(tt(1:ix)), tt(ix:len));
     endfor
     device="$device";
     plSetOpt("dev", device);
@@ -114,14 +114,14 @@ if ! isempty (failed)
     exit (1);
 endif
 EOF
-status_code=$?
-cat test.error
-if [ "$status_code" -ne 0 ]; then
-  exit $status_code
-fi
+    status_code=$?
+    cat test.error
+    if [ "$status_code" -ne 0 ]; then
+	exit $status_code
+    fi
 # Look for any PLPLOT ERROR messages from plwarn that do not result in an
 # exit code.
-is_error=`grep -l 'PLPLOT ERROR' test.error`
-if test -n "$is_error"; then
-  exit 1
-fi
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+	exit 1
+    fi
diff --git a/plplot_test/test_perl.sh.in b/plplot_test/test_perl.sh.in
--- a/plplot_test/test_perl.sh.in
+++ b/plplot_test/test_perl.sh.in
@@ -32,40 +32,40 @@
 # tree and install tree.
 lang="pdl"
 if [ "$LD_LIBRARY_PATH" = "" ] ; then
-  export LD_LIBRARY_PATH=../src:@LIB_DIR@
+    export LD_LIBRARY_PATH=../src:@LIB_DIR@
 else
-  export LD_LIBRARY_PATH=../src:@LIB_DIR@:$LD_LIBRARY_PATH
+    export LD_LIBRARY_PATH=../src:@LIB_DIR@:$LD_LIBRARY_PATH
 fi
 
 if [ "@HAVE_PDL_GRAPHICS_PLPLOT_40@" = "ON" ] ; then
-  INDEX_LIST="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 19 20 21 22 23 24 25 26 27 28 29 30 31"
+    INDEX_LIST="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 19 20 21 22 23 24 25 26 27 28 29 30 31"
 else
   # Examples 02, 20, 21, 23, 24, 28, 29, and 30 require PDL::Graphics::PLplot
   # version 0.46 or later.
-  INDEX_LIST="01 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 19 22 25 26 27"
+    INDEX_LIST="01 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 19 22 25 26 27"
 fi
 
 for index in $INDEX_LIST ; do
-  if [ "$verbose_test" ]; then
-    echo "x${index}.pl"
-  fi
-  if [ "$index" = "14" ] ; then
-    $perldir/x${index}.pl -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt << EOF
+    if [ "$verbose_test" ]; then
+	echo "x${index}.pl"
+    fi
+    if [ "$index" = "14" ] ; then
+	$perldir/x${index}.pl -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt << EOF
 ${OUTPUT_DIR}/x${index}a${lang}%n.$dsuffix
 EOF
-    status_code=$?
-  else
-    $perldir/x${index}.pl -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt
-    status_code=$?
-  fi
-  cat test.error
-  if [ "$status_code" -ne 0 ]; then
-    exit $status_code
-  fi
+	status_code=$?
+    else
+	$perldir/x${index}.pl -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt
+	status_code=$?
+    fi
+    cat test.error
+    if [ "$status_code" -ne 0 ]; then
+	exit $status_code
+    fi
   # Look for any PLPLOT ERROR messages from plwarn that do not result in an
   # exit code.
-  is_error=`grep -l 'PLPLOT ERROR' test.error`
-  if test -n "$is_error"; then
-    exit 1
-  fi
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+	exit 1
+    fi
 done
diff --git a/plplot_test/test_python.sh.in b/plplot_test/test_python.sh.in
--- a/plplot_test/test_python.sh.in
+++ b/plplot_test/test_python.sh.in
@@ -32,27 +32,27 @@
 # For 24 you need special fonts installed to get good result.
 lang="p"
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 \
-20 22 23 24 25 26 27 28 29 30 31 @NUMPY_EXAMPLES@ ; do
-  if [ "$verbose_test" ]; then
-    echo "x${index}"
-  fi
-  if [ "$index" = "14" ] ; then
-    @PYTHON_EXECUTABLE@ $pythondir/x$index -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt  << EOF
+    20 22 23 24 25 26 27 28 29 30 31 @NUMPY_EXAMPLES@ ; do
+    if [ "$verbose_test" ]; then
+	echo "x${index}"
+    fi
+    if [ "$index" = "14" ] ; then
+	@PYTHON_EXECUTABLE@ $pythondir/x$index -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt  << EOF
 ${OUTPUT_DIR}/x${index}a${lang}%n.$dsuffix
 EOF
-    status_code=$?
-  else
-    @PYTHON_EXECUTABLE@ $pythondir/x$index -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt 
-    status_code=$?
-  fi
-  cat test.error
-  if [ "$status_code" -ne 0 ]; then
-    exit $status_code
-  fi
+	status_code=$?
+    else
+	@PYTHON_EXECUTABLE@ $pythondir/x$index -dev $device -o ${OUTPUT_DIR}/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${OUTPUT_DIR}/x${index}${lang}_${dsuffix}.txt 
+	status_code=$?
+    fi
+    cat test.error
+    if [ "$status_code" -ne 0 ]; then
+	exit $status_code
+    fi
   # Look for any PLPLOT ERROR messages from plwarn that do not result in an
   # exit code.
-  is_error=`grep -l 'PLPLOT ERROR' test.error`
-  if test -n "$is_error"; then
-    exit 1
-  fi
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+	exit 1
+    fi
 done
diff --git a/plplot_test/test_tcl.sh.in b/plplot_test/test_tcl.sh.in
--- a/plplot_test/test_tcl.sh.in
+++ b/plplot_test/test_tcl.sh.in
@@ -29,7 +29,7 @@ results=`pwd`
 export results
 cd $tcldir
 if [ "$verbose_test" ]; then
-  echo "pltcl demo of plot"
+    echo "pltcl demo of plot"
 fi
 pltcl -dev $device -o $results/plot%n.$dsuffix $options <<EOF 2> test.error
 plinit
@@ -43,16 +43,16 @@ EOF
 status_code=$?
 cat test.error
 if [ "$status_code" -ne 0 ]; then
-  exit $status_code
+    exit $status_code
 fi
 # Look for any PLPLOT ERROR messages from plwarn that do not result in an
 # exit code.
 is_error=`grep -l 'PLPLOT ERROR' test.error`
 if test -n "$is_error"; then
-  exit 1
+    exit 1
 fi
 if [ "$verbose_test" ]; then
-  echo "pltcl demo of plgrid"
+    echo "pltcl demo of plgrid"
 fi
 pltcl -dev $device -o $results/plgrid%n.$dsuffix $options <<EOF 2> test.error
 plinit
@@ -63,38 +63,38 @@ EOF
 status_code=$?
 cat test.error
 if [ "$status_code" -ne 0 ]; then
-  exit $status_code
+    exit $status_code
 fi
 # Look for any PLPLOT ERROR messages from plwarn that do not result in an
 # exit code.
 is_error=`grep -l 'PLPLOT ERROR' test.error`
 if test -n "$is_error"; then
-  exit 1
+    exit 1
 fi
 # Skip 17th example because it is not implemented (and if it was, it
 # would be interactive only).
 # Other examples are not yet implemented.
 for index in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 18 20 21 22 23 24 25 26 27 28 29 30 31; do
-  if [ "$verbose_test" ]; then
-    echo "x${index}"
-  fi
-  if [ "$index" = "14" ] ; then
-    ./x${index} -dev $device -o $results/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${results}/x${index}${lang}_${dsuffix}.txt << EOF
+    if [ "$verbose_test" ]; then
+	echo "x${index}"
+    fi
+    if [ "$index" = "14" ] ; then
+	./x${index} -dev $device -o $results/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${results}/x${index}${lang}_${dsuffix}.txt << EOF
 ${results}/x${index}a${lang}%n.$dsuffix
 EOF
-    status_code=$?
-  else
-    ./x${index} -dev $device -o $results/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${results}/x${index}${lang}_${dsuffix}.txt
-    status_code=$?
-  fi
-  cat test.error
-  if [ "$status_code" -ne 0 ]; then
-    exit $status_code
-  fi
+	status_code=$?
+    else
+	./x${index} -dev $device -o $results/x${index}${lang}%n.$dsuffix $options 2> test.error >| ${results}/x${index}${lang}_${dsuffix}.txt
+	status_code=$?
+    fi
+    cat test.error
+    if [ "$status_code" -ne 0 ]; then
+	exit $status_code
+    fi
   # Look for any PLPLOT ERROR messages from plwarn that do not result in an
   # exit code.
-  is_error=`grep -l 'PLPLOT ERROR' test.error`
-  if test -n "$is_error"; then
-    exit 1
-  fi
+    is_error=`grep -l 'PLPLOT ERROR' test.error`
+    if test -n "$is_error"; then
+	exit 1
+    fi
 done
