Respamulated.
svn path=/trunk/; revision=1951

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -240,6 +240,8 @@ ac_help="$ac_help
   --enable-tk             enable tk device driver ($enable_tk)"
 ac_help="$ac_help
   --enable-dp             enable dp device driver ($enable_dp)"
+ac_help="$ac_help
+  --enable-pbm            enable pbm device driver ($enable_pbm)"
 ac_default_prefix=/usr/local/plplot
 ac_help="$ac_help
   --with-x                use the X Window System"
@@ -1339,6 +1341,27 @@ EOF
 else
     enable_dp="no"
 fi
+# Check whether --enable-pbm or --disable-pbm was given.
+enableval="$enable_pbm"
+if test -n "$enableval"; then
+  :
+fi
+# Check whether --with-pbm or --without-pbm was given.
+withval="$with_pbm"
+if test -n "$withval"; then
+  { echo "configure: error: unrecognized variable: with_pbm" 1>&2; exit 1; }
+fi
+
+if test "$enable_pbm" = "yes" -o "$enable_pbm $enable_drivers" = " yes"; then
+    enable_pbm="yes"
+    cat >> confdefs.h <<\EOF
+#define PLD_pbm 1
+EOF
+
+    DEVICES="$DEVICES pbm"
+else
+    enable_pbm="no"
+fi
 
 
 # ----------------------------------------------------------------------------
@@ -2100,7 +2123,7 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 2104 "configure"
+#line 2127 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
@@ -2114,7 +2137,7 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 2118 "configure"
+#line 2141 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
@@ -2261,7 +2284,7 @@ test -z "$x_direct_test_library" && x_direct_test_library=Xt
 test -z "$x_direct_test_function" && x_direct_test_function=XtMalloc
 test -z "$x_direct_test_include" && x_direct_test_include=X11/Intrinsic.h
 cat > conftest.$ac_ext <<EOF
-#line 2265 "configure"
+#line 2288 "configure"
 #include "confdefs.h"
 #include <$x_direct_test_include>
 EOF
@@ -2324,7 +2347,7 @@ rm -f conftest*
 ac_save_LIBS="$LIBS"
 LIBS="-l$x_direct_test_library $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2328 "configure"
+#line 2351 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -2410,7 +2433,7 @@ fi
 	XINCDIR="$x_includes"
 	if test -z "$XINCDIR"; then
 	    cat > conftest.$ac_ext <<EOF
-#line 2414 "configure"
+#line 2437 "configure"
 #include "confdefs.h"
 #include <X11/Intrinsic.h>
 EOF
@@ -2467,7 +2490,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lX11  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2471 "configure"
+#line 2494 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3385,7 +3408,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lf2c  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3389 "configure"
+#line 3412 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3455,7 +3478,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lXbsd  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3459 "configure"
+#line 3482 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3488,7 +3511,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lsocket  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3492 "configure"
+#line 3515 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3521,7 +3544,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lnsl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3525 "configure"
+#line 3548 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3554,7 +3577,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lieee  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3558 "configure"
+#line 3581 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3587,7 +3610,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lm  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3591 "configure"
+#line 3614 "configure"
 #include "confdefs.h"
 
 int main() { return 0; }
@@ -3763,7 +3786,7 @@ else
   ac_cv_c_cross=yes
 else
 cat > conftest.$ac_ext <<EOF
-#line 3767 "configure"
+#line 3790 "configure"
 #include "confdefs.h"
 main(){return(0);}
 EOF
@@ -3784,7 +3807,7 @@ if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3788 "configure"
+#line 3811 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -3806,7 +3829,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 3810 "configure"
+#line 3833 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -3824,7 +3847,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 3828 "configure"
+#line 3851 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -3845,7 +3868,7 @@ if test "$cross_compiling" = yes; then
   ac_cv_header_stdc=no
 else
 cat > conftest.$ac_ext <<EOF
-#line 3849 "configure"
+#line 3872 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -3882,7 +3905,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3886 "configure"
+#line 3909 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
@@ -3943,7 +3966,7 @@ if eval "test \"`echo '$''{'ac_cv_type_pid_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3947 "configure"
+#line 3970 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -3975,7 +3998,7 @@ if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3979 "configure"
+#line 4002 "configure"
 #include "confdefs.h"
 #include <vfork.h>
 EOF
@@ -4009,7 +4032,7 @@ else
   ac_cv_func_vfork=no
 else
 cat > conftest.$ac_ext <<EOF
-#line 4013 "configure"
+#line 4036 "configure"
 #include "confdefs.h"
 /* Thanks to Paul Eggert for this test.  */
 #include <stdio.h>
@@ -4124,7 +4147,7 @@ if eval "test \"`echo '$''{'ac_cv_func_popen'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 4128 "configure"
+#line 4151 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char popen(); below.  */
@@ -4179,7 +4202,7 @@ if eval "test \"`echo '$''{'ac_cv_type_caddr_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 4183 "configure"
+#line 4206 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
