Added eps2jpeg.pl.in and tex2eps.pl.in configure.in checks for latex, dvips and mogrify
svn path=/trunk/; revision=2152

diff --git a/doc/docbook-sgml/src/configure b/doc/docbook-sgml/src/configure
--- a/doc/docbook-sgml/src/configure
+++ b/doc/docbook-sgml/src/configure
@@ -24,6 +24,15 @@ ac_help="$ac_help
 ac_help="$ac_help
 
   --with-perl=PATH/PERL		Alternative perl program"
+ac_help="$ac_help
+
+  --with-mogrify=PATH/MOGRIFY		Alternative mogrify program"
+ac_help="$ac_help
+
+  --with-latex=PATH/LATEX		Alternative latex program"
+ac_help="$ac_help
+
+  --with-dvips=PATH/DVIPS		Alternative dvips program"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -540,7 +549,7 @@ fi
 dsssl_dtd_pubid="-//James Clark//DTD DSSSL Style Sheet//EN"
 db_ss_html_pubid="-//Norman Walsh//DOCUMENT DocBook HTML Stylesheet//EN"
 db_ss_print_pubid="-//Norman Walsh//DOCUMENT DocBook Print Stylesheet//EN"
-docbook_dtd_pubid="-//OASIS//DTD DocBook V3.1//ENN"
+docbook_dtd_pubid="-//OASIS//DTD DocBook V3.1//EN"
 
 
 
@@ -593,7 +602,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:597: checking for $ac_word" >&5
+echo "configure:606: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_JADE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -651,7 +660,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:655: checking for $ac_word" >&5
+echo "configure:664: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_JADETEX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -709,7 +718,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:713: checking for $ac_word" >&5
+echo "configure:722: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -744,6 +753,180 @@ if test x = x$PERL ; then
     Install the perl program in your path or specify its
     location with the option --with-perl.  The perl package can be 
     found at http://www.perl.com." 1>&2; exit 1; }
+fi
+
+
+
+
+
+
+
+
+# Check whether --with-mogrify or --without-mogrify was given.
+if test "${with_mogrify+set}" = set; then
+  withval="$with_mogrify"
+  mogrify_prog=$withval
+else
+  mogrify_prog=mogrify
+fi
+
+
+for ac_prog in $mogrify_prog
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:780: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_MOGRIFY'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$MOGRIFY"; then
+  ac_cv_prog_MOGRIFY="$MOGRIFY" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_MOGRIFY="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+MOGRIFY="$ac_cv_prog_MOGRIFY"
+if test -n "$MOGRIFY"; then
+  echo "$ac_t""$MOGRIFY" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$MOGRIFY" && break
+done
+
+
+if test x = x$MOGRIFY ; then
+ { echo "configure: error: Program mogrify not found.  
+    Install the mogrify program in your path or specify its
+    location with the option --with-mogrify.  The mogrify package can be 
+    found at Imagemagick." 1>&2; exit 1; }
+fi
+
+
+
+
+
+
+
+
+# Check whether --with-latex or --without-latex was given.
+if test "${with_latex+set}" = set; then
+  withval="$with_latex"
+  latex_prog=$withval
+else
+  latex_prog=latex
+fi
+
+
+for ac_prog in $latex_prog
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:838: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_LATEX'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$LATEX"; then
+  ac_cv_prog_LATEX="$LATEX" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_LATEX="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+LATEX="$ac_cv_prog_LATEX"
+if test -n "$LATEX"; then
+  echo "$ac_t""$LATEX" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$LATEX" && break
+done
+
+
+if test x = x$LATEX ; then
+ { echo "configure: error: Program latex not found.  
+    Install the latex program in your path or specify its
+    location with the option --with-latex.  The latex package can be 
+    found at http://www.ctan.org." 1>&2; exit 1; }
+fi
+
+
+
+
+
+
+
+
+# Check whether --with-dvips or --without-dvips was given.
+if test "${with_dvips+set}" = set; then
+  withval="$with_dvips"
+  dvips_prog=$withval
+else
+  dvips_prog=dvips
+fi
+
+
+for ac_prog in $dvips_prog
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:896: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_DVIPS'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$DVIPS"; then
+  ac_cv_prog_DVIPS="$DVIPS" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_DVIPS="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+DVIPS="$ac_cv_prog_DVIPS"
+if test -n "$DVIPS"; then
+  echo "$ac_t""$DVIPS" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$DVIPS" && break
+done
+
+
+if test x = x$DVIPS ; then
+ { echo "configure: error: Program dvips not found.  
+    Install the dvips program in your path or specify its
+    location with the option --with-dvips.  The dvips package can be 
+    found at http://www.ctan.org." 1>&2; exit 1; }
 fi
 
 
@@ -959,7 +1142,7 @@ done
 
 ac_given_srcdir=$srcdir
 
-trap 'rm -fr `echo "Makefile" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "Makefile eps2jpeg.pl  tex2eps.pl" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -995,6 +1178,9 @@ s%@SGML_CATALOGS@%$SGML_CATALOGS%g
 s%@JADE@%$JADE%g
 s%@JADETEX@%$JADETEX%g
 s%@PERL@%$PERL%g
+s%@MOGRIFY@%$MOGRIFY%g
+s%@LATEX@%$LATEX%g
+s%@DVIPS@%$DVIPS%g
 
 CEOF
 EOF
@@ -1036,7 +1222,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"Makefile"}
+CONFIG_FILES=\${CONFIG_FILES-"Makefile eps2jpeg.pl  tex2eps.pl"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
@@ -1101,3 +1287,4 @@ EOF
 chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
+
